### ISSUE TITLE
This repository is empty.

### ISSUE THREAD

**Issue by jucasoft** [dvddpl/dvddpl.github.io#1]
?

**Comment by dvddpl** [comment]
Ciao Luca!  buon anno!
come va?

*Davide de Paolis*
Technical Lead - Strategic Projects
GoodGameStudios - Altigi GmbH <http://www.goodgamestudios.com/>

Mobile DE: +4915731972570



Il giorno mer 23 dic 2020 alle ore 14:21 jucasoft <notifications@github.com>
ha scritto:

**Comment by jucasoft** [comment]
sono entrato quasi per caso.
mi stavo chiedevo per quale motivo non rispondessi.
ed invece...

buon anno a te, io sto alla grande, nonostante il periodo.

nelle issues di github non mettono data e ora nei commenti?

hai la firma figosa? wow "Technical Lead - Strategic Projects"
come ti vanno le cose?

**Comment by dvddpl** [comment]
ciao.  sinceramente non so.  non uso moltissimo github ( a parte per codice
altrui).  ho creato questa repo perche ho scoperto che puoi costruirti siti
statici a partire dal markdown ( e in pratica posso spostare il mio blog li)

anche a me van bene.  un po una palla che tutto chiuso e non posso fare
sport, ma per il resto bene.  i bimbi fanno scuola da casa.  io sto
lavorando da casa da marzo. ( fatto 1 mese a lavorare dal mare
questestate 😎).   e spero di non dover mai piu tornare a lavorare in un
ufficio.
Si si  cho la firma figa,   il titolo quello e' per quanto.. niente di che
,  e il mio  Team si chiama cosi perche facciamo cose importanti  :-)

te che fai?  ho visto oggi in linkedin anniversario Cornalba 16 in
sysline/gpi.   tu?




*Davide de Paolis*
Technical Lead - Strategic Projects
GoodGameStudios - Altigi GmbH <http://www.goodgamestudios.com/>

Mobile DE: +4915731972570



Il giorno mar 5 gen 2021 alle ore 14:19 jucasoft <notifications@github.com>
ha scritto:

**Comment by jucasoft** [comment]
pure io lavoro da casa, non credevo di adattarmi cosi velocemente.
da giugno 2018 lavoro per una grande realtà consustanziale come sviluppatore e formatore Angular.
un paio di mesi fa sono riuscito a fare un corso online di una settimana a dei colleghi, una bellissima esperienza.
come piattaforma online di supporto ho usato github https://github.com/jucasoft/corso-angular-ngrx

**Comment by dvddpl** [comment]
wow.   ho guardato su linkedin e pure tu hai un bel titolo : Advanced
Consultant    :-)
Altran e'la societa dove lavora o lavorava Sommaruga no?


come e' la realta da consulente.    a  me interesserebbe provare,  anche
perche spesso i soldi son di pi che da semplice dipendente,  ma ho anche
paura che poi lacopndizioni lavorative non siano poi ottimali e soprattuto
non mi piacerebbe cambiare contesto cosi di frequente ( per quanto in home
working  sarebbe anche fattibile)

:-)

*Davide de Paolis*
Technical Lead - Strategic Projects
GoodGameStudios - Altigi GmbH <http://www.goodgamestudios.com/>

Mobile DE: +4915731972570



Il giorno mar 5 gen 2021 alle ore 20:13 jucasoft <notifications@github.com>
ha scritto:

**Comment by jucasoft** [comment]
Ormai lo faccio da cosi' tanto tempo che non ti saprei dire se esiste una differenza, non ho mai lavorato per società di prodotto come la tua.
Nonostante le molte offerte che arrivano, non sono per nulla attratto a cambiare, questo vuol dire che mi trovo bene. 
Sono arrivato al punto di sfoltire i contatti di Linkedin.
La combinazione tra, persone che conosco/nuovi progetti e' + che positiva.
Ho la fortuna di trovare ancora interessante quello che faccio, non sono ancora arrivato al punto di voler aprire un agriturismo in Australia, classica situazione di quando cala la libido per il codice.

L'idea di mettere il tuo blog su github e` interessante, ma tieni conto dei casini nel dover aggiornare gli articoli, git hub e` adatto a siti statici. io opterei per altra roba, no?

**Comment by dvddpl** [comment]
mi sono accorto che ci stiamo scrivendo sulla issue di github...
spero tu abbia ancora la mail su gmail , ti ho scritto di la direttamente.
:-)

*Davide de Paolis*
Technical Lead - Strategic Projects
GoodGameStudios - Altigi GmbH <http://www.goodgamestudios.com/>

Mobile DE: +4915731972570



Il giorno mer 6 gen 2021 alle ore 08:06 jucasoft <notifications@github.com>
ha scritto:
